version: "3.3"

services: 
  basededatos:
    image: mysql
    container_name: basededatos
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'challengeteatro'
      MYSQL_USER: 'myuser'
      MYSQL_PASSWORD: 'passworduser'
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./dbdata:/var/lib/mysql
    command: mysqld --default-authentication-plugin=mysql_native_password


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - basededatos
    environment:
      PMA_HOST: 'basededatos'
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8080:80


  laravel:
    build:
      context: ./source
    container_name: laravel
    environment:
      DB_HOST: basededatos
      DB_PORT: 3306
      DB_DATABASE: 'challengeteatro'
      DB_USERNAME: 'root'
      DB_PASSWORD: 'root'
    ports: 
      - 8000:8000
    depends_on: 
      - basededatos
    volumes:
      - ./code:/var/www


